
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author BernierCorentin
 */
public class Menu extends javax.swing.JPanel {

    private Fenetre laFen;
    private JTextField lesTFs[];

    /**
     * Creates new form Menu
     */
    public Menu(Fenetre laFen) {
        initComponents();
        lesTFs = new JTextField[]{jTFNomJ1, jTFNomJ2, jTFNomJ3, jTFNomJ4, jTFNomJ5, jTFNomJ6, jTFNomJ7, jTFNomJ8};
        this.laFen = laFen;
        for (int i = 2; i < lesTFs.length; i++) {
            lesTFs[i].setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpnNbJoueurHumain = new javax.swing.JSpinner();
        jSpnNbJoueurAI = new javax.swing.JSpinner();
        jTFNomJ1 = new javax.swing.JTextField();
        jTFNomJ2 = new javax.swing.JTextField();
        jTFNomJ3 = new javax.swing.JTextField();
        jTFNomJ4 = new javax.swing.JTextField();
        jTFNomJ5 = new javax.swing.JTextField();
        jTFNomJ6 = new javax.swing.JTextField();
        jTFNomJ7 = new javax.swing.JTextField();
        jTFNomJ8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1366, 768));

        jSpnNbJoueurHumain.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jSpnNbJoueurHumain.setModel(new javax.swing.SpinnerNumberModel(2, 0, 8, 1));
        jSpnNbJoueurHumain.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpnNbJoueurHumainStateChanged(evt);
            }
        });

        jSpnNbJoueurAI.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jSpnNbJoueurAI.setModel(new javax.swing.SpinnerNumberModel(2, 0, 8, 1));
        jSpnNbJoueurAI.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpnNbJoueurAIStateChanged(evt);
            }
        });

        jTFNomJ1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jTFNomJ1.setToolTipText("");

        jTFNomJ2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jTFNomJ2.setToolTipText("");

        jTFNomJ3.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jTFNomJ3.setToolTipText("");

        jTFNomJ4.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jTFNomJ4.setToolTipText("");

        jTFNomJ5.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jTFNomJ5.setToolTipText("");

        jTFNomJ6.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jTFNomJ6.setToolTipText("");

        jTFNomJ7.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jTFNomJ7.setToolTipText("");

        jTFNomJ8.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jTFNomJ8.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setText("Nombre de Joueur Humain");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel2.setText("Nombre d'IAs");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel3.setText("Noms des Joueurs Humains");

        jButton1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jButton1.setText("Commencer la partie");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpnNbJoueurAI, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpnNbJoueurHumain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFNomJ4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTFNomJ8, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTFNomJ3, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                    .addComponent(jTFNomJ1)
                                    .addComponent(jTFNomJ2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFNomJ6)
                                    .addComponent(jTFNomJ5, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                    .addComponent(jTFNomJ7))))
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(352, 352, 352))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpnNbJoueurHumain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpnNbJoueurAI))
                .addGap(71, 71, 71)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNomJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNomJ5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNomJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNomJ6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNomJ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNomJ7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNomJ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNomJ8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSpnNbJoueurHumainStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpnNbJoueurHumainStateChanged
        for (int i = 0; i < lesTFs.length; i++) {
            if (i < (int) jSpnNbJoueurHumain.getValue()) {
                lesTFs[i].setEnabled(true);
            } else {
                lesTFs[i].setEnabled(false);
            }
        }
        if ((int) jSpnNbJoueurHumain.getValue() + (int) jSpnNbJoueurAI.getValue() > 8) {
            jSpnNbJoueurAI.setValue((int) jSpnNbJoueurAI.getValue() - 1);
        }
    }//GEN-LAST:event_jSpnNbJoueurHumainStateChanged

    private void jSpnNbJoueurAIStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpnNbJoueurAIStateChanged
        if ((int) jSpnNbJoueurHumain.getValue() + (int) jSpnNbJoueurAI.getValue() > 8) {
            jSpnNbJoueurHumain.setValue((int) jSpnNbJoueurHumain.getValue() - 1);
        }
    }//GEN-LAST:event_jSpnNbJoueurAIStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ((int) jSpnNbJoueurHumain.getValue() + (int) jSpnNbJoueurAI.getValue() < 9 && (int) jSpnNbJoueurHumain.getValue() + (int) jSpnNbJoueurAI.getValue() > 1) {
            String lesNomsHumains[] = new String[(int) jSpnNbJoueurHumain.getValue()];
            for (int i = 0; i < (int) jSpnNbJoueurHumain.getValue(); i++) {
                lesNomsHumains[i] = lesTFs[i].getText();
            }
            laFen.commencerPartie((int) jSpnNbJoueurHumain.getValue(), (int) jSpnNbJoueurAI.getValue(), lesNomsHumains);
        } else {
            if ((int) jSpnNbJoueurHumain.getValue() + (int) jSpnNbJoueurAI.getValue() > 8) {
                JOptionPane.showMessageDialog(this, "Total de 8 joueurs maximum", "Inane error", JOptionPane.ERROR_MESSAGE);
            } else if ((int) jSpnNbJoueurHumain.getValue() + (int) jSpnNbJoueurAI.getValue() < 2) {
                JOptionPane.showMessageDialog(this, "Total minimum de 2 joueurs", "Inane error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpnNbJoueurAI;
    private javax.swing.JSpinner jSpnNbJoueurHumain;
    private javax.swing.JTextField jTFNomJ1;
    private javax.swing.JTextField jTFNomJ2;
    private javax.swing.JTextField jTFNomJ3;
    private javax.swing.JTextField jTFNomJ4;
    private javax.swing.JTextField jTFNomJ5;
    private javax.swing.JTextField jTFNomJ6;
    private javax.swing.JTextField jTFNomJ7;
    private javax.swing.JTextField jTFNomJ8;
    // End of variables declaration//GEN-END:variables
}
